### ISSUE TITLE
But no cache (Netlify Function with query strings ignores custom Cache-Control header)

### ISSUE THREAD

**Issue by TigersWay** [11ty/eleventy-img-cloud#1]
Hi Zach,
You surely know better or can get better information, but it seems caching is not really possible that way: [Netlify Function with query strings ignores custom Cache-Control header](https://community.netlify.com/t/netlify-function-with-query-strings-ignores-custom-cache-control-header/15390).
I tried last year and only the first image and first size was working!

Any hope you can set a "caching" system?

**Comment by zachleat** [comment]
Yeah I think there are some hefty production limitations here—definitely not ready for production use. I added a warning to the README to reflect this.

You might get some mileage out of using it to supplement a super large build (and save those images locally) but you’re probably better off running it locally for now.

More to come!
